name: Erlang CI

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch || 'master') }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ["27", "28"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v5
    - uses: erlef/setup-beam@v1
      id: setup-beam
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: "3"
    - name: Compile
      run: make compile
    - name: Check format
      run: make check-format
    - name: Run xref
      run: make xref
    - name: Fetch PLT
      uses: actions/cache@v4
      id: cache-plt
      with:
        path: |
          _build/default/*_plt
        key: dialyzer-${{ github.ref_name }}-${{ matrix.otp }}
        restore-keys: |
          dialyzer-${{ github.event.repository.default_branch || 'master' }}-${{ matrix.otp }}
          dialyzer-${{ github.event.repository.default_branch || 'master' }}-
    - name: Run dialyzer
      run: make dialyze
    - name: Run eunit tests
      run: make eunit
    - name: Run ct tests
      run: make ct

  release:
    if: github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, 'no-release:') == false
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
